[project]
name = "aws-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bedrock-agentcore-starter-toolkit>=0.1.32",
]

[tool.uv.workspace]
members = [
    "agent_deployment",
]
